/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { ClientWhereUniqueInput } from "../../client/base/ClientWhereUniqueInput";
import { ValidateNested, IsOptional } from "class-validator";
import { Type } from "class-transformer";
import { StringFilter } from "../../util/StringFilter";
import { FactureListRelationFilter } from "../../facture/base/FactureListRelationFilter";
import { LigneCommandeListRelationFilter } from "../../ligneCommande/base/LigneCommandeListRelationFilter";

@InputType()
class CommandeWhereInput {
  @ApiProperty({
    required: false,
    type: () => ClientWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => ClientWhereUniqueInput)
  @IsOptional()
  @Field(() => ClientWhereUniqueInput, {
    nullable: true,
  })
  client_id?: ClientWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  etat?: StringFilter;

  @ApiProperty({
    required: false,
    type: () => FactureListRelationFilter,
  })
  @ValidateNested()
  @Type(() => FactureListRelationFilter)
  @IsOptional()
  @Field(() => FactureListRelationFilter, {
    nullable: true,
  })
  factures?: FactureListRelationFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: () => LigneCommandeListRelationFilter,
  })
  @ValidateNested()
  @Type(() => LigneCommandeListRelationFilter)
  @IsOptional()
  @Field(() => LigneCommandeListRelationFilter, {
    nullable: true,
  })
  ligneCommandes?: LigneCommandeListRelationFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  montantTotal?: StringFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  numeroCommande?: StringFilter;
}

export { CommandeWhereInput as CommandeWhereInput };
