/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  MaxLength,
  ValidateNested,
  IsOptional,
} from "class-validator";
import { ClientWhereUniqueInput } from "../../client/base/ClientWhereUniqueInput";
import { Type } from "class-transformer";
import { FactureCreateNestedManyWithoutCommandesInput } from "./FactureCreateNestedManyWithoutCommandesInput";
import { LigneCommandeCreateNestedManyWithoutCommandesInput } from "./LigneCommandeCreateNestedManyWithoutCommandesInput";

@InputType()
class CommandeCreateInput {
  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @Field(() => String)
  ateCommande!: string;

  @ApiProperty({
    required: false,
    type: () => ClientWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => ClientWhereUniqueInput)
  @IsOptional()
  @Field(() => ClientWhereUniqueInput, {
    nullable: true,
  })
  client_id?: ClientWhereUniqueInput | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @Field(() => String)
  etat!: string;

  @ApiProperty({
    required: false,
    type: () => FactureCreateNestedManyWithoutCommandesInput,
  })
  @ValidateNested()
  @Type(() => FactureCreateNestedManyWithoutCommandesInput)
  @IsOptional()
  @Field(() => FactureCreateNestedManyWithoutCommandesInput, {
    nullable: true,
  })
  factures?: FactureCreateNestedManyWithoutCommandesInput;

  @ApiProperty({
    required: false,
    type: () => LigneCommandeCreateNestedManyWithoutCommandesInput,
  })
  @ValidateNested()
  @Type(() => LigneCommandeCreateNestedManyWithoutCommandesInput)
  @IsOptional()
  @Field(() => LigneCommandeCreateNestedManyWithoutCommandesInput, {
    nullable: true,
  })
  ligneCommandes?: LigneCommandeCreateNestedManyWithoutCommandesInput;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @Field(() => String)
  montantTotal!: string;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @Field(() => String)
  numeroCommande!: string;
}

export { CommandeCreateInput as CommandeCreateInput };
