/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  MaxLength,
  IsOptional,
  ValidateNested,
} from "class-validator";
import { ClientWhereUniqueInput } from "../../client/base/ClientWhereUniqueInput";
import { Type } from "class-transformer";
import { FactureUpdateManyWithoutCommandesInput } from "./FactureUpdateManyWithoutCommandesInput";
import { LigneCommandeUpdateManyWithoutCommandesInput } from "./LigneCommandeUpdateManyWithoutCommandesInput";

@InputType()
class CommandeUpdateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  ateCommande?: string;

  @ApiProperty({
    required: false,
    type: () => ClientWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => ClientWhereUniqueInput)
  @IsOptional()
  @Field(() => ClientWhereUniqueInput, {
    nullable: true,
  })
  client_id?: ClientWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  etat?: string;

  @ApiProperty({
    required: false,
    type: () => FactureUpdateManyWithoutCommandesInput,
  })
  @ValidateNested()
  @Type(() => FactureUpdateManyWithoutCommandesInput)
  @IsOptional()
  @Field(() => FactureUpdateManyWithoutCommandesInput, {
    nullable: true,
  })
  factures?: FactureUpdateManyWithoutCommandesInput;

  @ApiProperty({
    required: false,
    type: () => LigneCommandeUpdateManyWithoutCommandesInput,
  })
  @ValidateNested()
  @Type(() => LigneCommandeUpdateManyWithoutCommandesInput)
  @IsOptional()
  @Field(() => LigneCommandeUpdateManyWithoutCommandesInput, {
    nullable: true,
  })
  ligneCommandes?: LigneCommandeUpdateManyWithoutCommandesInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  montantTotal?: string;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  numeroCommande?: string;
}

export { CommandeUpdateInput as CommandeUpdateInput };
