/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { ProduitService } from "../produit.service";
import { ProduitCreateInput } from "./ProduitCreateInput";
import { Produit } from "./Produit";
import { ProduitFindManyArgs } from "./ProduitFindManyArgs";
import { ProduitWhereUniqueInput } from "./ProduitWhereUniqueInput";
import { ProduitUpdateInput } from "./ProduitUpdateInput";
import { LigneCommandeFindManyArgs } from "../../ligneCommande/base/LigneCommandeFindManyArgs";
import { LigneCommande } from "../../ligneCommande/base/LigneCommande";
import { LigneCommandeWhereUniqueInput } from "../../ligneCommande/base/LigneCommandeWhereUniqueInput";

export class ProduitControllerBase {
  constructor(protected readonly service: ProduitService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Produit })
  async createProduit(
    @common.Body() data: ProduitCreateInput
  ): Promise<Produit> {
    return await this.service.createProduit({
      data: data,
      select: {
        categorie: true,
        createdAt: true,
        dateDajout: true,
        description: true,
        id: true,
        nom: true,
        prixAchat: true,
        prixVente: true,
        quantitStock: true,
        reference: true,
        statut: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Produit] })
  @ApiNestedQuery(ProduitFindManyArgs)
  async produits(@common.Req() request: Request): Promise<Produit[]> {
    const args = plainToClass(ProduitFindManyArgs, request.query);
    return this.service.produits({
      ...args,
      select: {
        categorie: true,
        createdAt: true,
        dateDajout: true,
        description: true,
        id: true,
        nom: true,
        prixAchat: true,
        prixVente: true,
        quantitStock: true,
        reference: true,
        statut: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Produit })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async produit(
    @common.Param() params: ProduitWhereUniqueInput
  ): Promise<Produit | null> {
    const result = await this.service.produit({
      where: params,
      select: {
        categorie: true,
        createdAt: true,
        dateDajout: true,
        description: true,
        id: true,
        nom: true,
        prixAchat: true,
        prixVente: true,
        quantitStock: true,
        reference: true,
        statut: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Produit })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateProduit(
    @common.Param() params: ProduitWhereUniqueInput,
    @common.Body() data: ProduitUpdateInput
  ): Promise<Produit | null> {
    try {
      return await this.service.updateProduit({
        where: params,
        data: data,
        select: {
          categorie: true,
          createdAt: true,
          dateDajout: true,
          description: true,
          id: true,
          nom: true,
          prixAchat: true,
          prixVente: true,
          quantitStock: true,
          reference: true,
          statut: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Produit })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteProduit(
    @common.Param() params: ProduitWhereUniqueInput
  ): Promise<Produit | null> {
    try {
      return await this.service.deleteProduit({
        where: params,
        select: {
          categorie: true,
          createdAt: true,
          dateDajout: true,
          description: true,
          id: true,
          nom: true,
          prixAchat: true,
          prixVente: true,
          quantitStock: true,
          reference: true,
          statut: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/ligneCommandes")
  @ApiNestedQuery(LigneCommandeFindManyArgs)
  async findLigneCommandes(
    @common.Req() request: Request,
    @common.Param() params: ProduitWhereUniqueInput
  ): Promise<LigneCommande[]> {
    const query = plainToClass(LigneCommandeFindManyArgs, request.query);
    const results = await this.service.findLigneCommandes(params.id, {
      ...query,
      select: {
        commande_id: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        prixUnitaire: true,

        produit_id: {
          select: {
            id: true,
          },
        },

        quantit: true,
        remise: true,
        totalLignes: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/ligneCommandes")
  async connectLigneCommandes(
    @common.Param() params: ProduitWhereUniqueInput,
    @common.Body() body: LigneCommandeWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      ligneCommandes: {
        connect: body,
      },
    };
    await this.service.updateProduit({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/ligneCommandes")
  async updateLigneCommandes(
    @common.Param() params: ProduitWhereUniqueInput,
    @common.Body() body: LigneCommandeWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      ligneCommandes: {
        set: body,
      },
    };
    await this.service.updateProduit({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/ligneCommandes")
  async disconnectLigneCommandes(
    @common.Param() params: ProduitWhereUniqueInput,
    @common.Body() body: LigneCommandeWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      ligneCommandes: {
        disconnect: body,
      },
    };
    await this.service.updateProduit({
      where: params,
      data,
      select: { id: true },
    });
  }
}
