/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  LigneCommande as PrismaLigneCommande,
  Commande as PrismaCommande,
  Produit as PrismaProduit,
} from "@prisma/client";

export class LigneCommandeServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.LigneCommandeCountArgs, "select">
  ): Promise<number> {
    return this.prisma.ligneCommande.count(args);
  }

  async ligneCommandes(
    args: Prisma.LigneCommandeFindManyArgs
  ): Promise<PrismaLigneCommande[]> {
    return this.prisma.ligneCommande.findMany(args);
  }
  async ligneCommande(
    args: Prisma.LigneCommandeFindUniqueArgs
  ): Promise<PrismaLigneCommande | null> {
    return this.prisma.ligneCommande.findUnique(args);
  }
  async createLigneCommande(
    args: Prisma.LigneCommandeCreateArgs
  ): Promise<PrismaLigneCommande> {
    return this.prisma.ligneCommande.create(args);
  }
  async updateLigneCommande(
    args: Prisma.LigneCommandeUpdateArgs
  ): Promise<PrismaLigneCommande> {
    return this.prisma.ligneCommande.update(args);
  }
  async deleteLigneCommande(
    args: Prisma.LigneCommandeDeleteArgs
  ): Promise<PrismaLigneCommande> {
    return this.prisma.ligneCommande.delete(args);
  }

  async getCommandeId(parentId: string): Promise<PrismaCommande | null> {
    return this.prisma.ligneCommande
      .findUnique({
        where: { id: parentId },
      })
      .commande_id();
  }

  async getProduitId(parentId: string): Promise<PrismaProduit | null> {
    return this.prisma.ligneCommande
      .findUnique({
        where: { id: parentId },
      })
      .produit_id();
  }
}
